dist: trusty

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

sudo: false

install:
  - travis_retry composer update --no-interaction --prefer-dist

script: vendor/bin/phpunit
